### ISSUE TITLE
Problems Running the Simulator

### ISSUE THREAD

**Issue by SamHSlva** [berkeleyopenarms/blue_simulator#2]
Initially, I'd like to congratulate about the initiative and the excellent work in this hardware and software, it has such a great potential for those, like me, interested in researching the gap between simulation training and hardware implementation of Reinforcement Learning.

With respect to the ROS Kinetic installation and posterior catkin_make, I have encountered several issues of missing packages. (I did a new clean and full install of ROS Kinetic).

The following commands were required after ROS installation, to be able to compile your packages into my workspace:

`sudo apt-get install ros-kinetic-serial`
`sudo apt install ros-kinetic-hardware-interface`
`sudo apt install ros-kinetic-transmission-interface`
`sudo apt install ros-kinetic-controller-interface`
`sudo apt install ros-kinetic-controller-manager`
`sudo apt install ros-kinetic-control-toolbox`
`sudo apt-get install ros-kinetic-rosbridge-server`

These allowed me to compile and finally run: `roslaunch blue_gazebo blue_world.launch`

The problem is that, while the roslauch worked, the following error launched:

`process[rosapi-11]: started with pid [14040]
registered capabilities (classes):
  rosbridge_library.capabilities.call_service.CallService
  rosbridge_library.capabilities.advertise.Advertise
  rosbridge_library.capabilities.publish.Publish
  rosbridge_library.capabilities.subscribe.Subscribe
  <class 'rosbridge_library.capabilities.defragmentation.Defragment'>
  rosbridge_library.capabilities.advertise_service.AdvertiseService
  rosbridge_library.capabilities.service_response.ServiceResponse
  rosbridge_library.capabilities.unadvertise_service.UnadvertiseService
[ERROR] [1555632039.674402, 0.000000]: ['blue_controllers/joint_state_controller']
[ERROR] [1555632039.674570, 0.000000]: []
[INFO] [1555632039.674686, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[ERROR] [1555632039.681402, 0.000000]: ['blue_controllers/joint_state_controller']
[ERROR] [1555632039.681646, 0.000000]: []`

And also the following warnings:

`[WARN] [1555632069.843173, 26.454000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[WARN] [1555632069.845441, 26.456000]: Controller Spawner couldn't find the expected controller_manager ROS interface.`

I believe, that because of those errors I am unable to call:

`rosservice call /right_arm/controller_manager/load_controller "blue_controllers/joint_ctc"`; consequently I have this error:

`ERROR: Service [/right_arm/controller_manager/load_controller] is not available.`

Please, Could you help me figure out, if I have missed any step, or if there is a bug on the current version?

Thank you.

**Comment by wuphilipp** [comment]
Hello @SamHSlva 
Thank you for the congratulations! We are really excited about the potential of this project as well!

Our package dependencies do need updating, so thanks for pointing that out! We will look into this and try to push a fix soon with updated instructions.

**Comment by SamHSlva** [comment]
Any idea on those errors that I am having?

**Comment by brentyi** [comment]
@SamHSlva can you try following the installation instructions in the README of the [blue_core](https://github.com/berkeleyopenarms/blue_core) repo***? The ones in this repo might be out-of-date or incomplete -- we're blocking off some time today to investigate/fix.

***edit: this will not fix your issue

**Comment by brentyi** [comment]
^ no fix yet, but quick update -- did an install on a clean copy of Ubuntu and am running into the same issue

**Comment by brentyi** [comment]
@SamHSlva we just pushed a fix and updated the install instructions -- could you try again?

thanks!

**Comment by SamHSlva** [comment]
@brentyi Thank you. It has worked.

**Comment by brentyi** [comment]
great :)

closing this, but let us know if any other issues pop up!
